This document contains all the reviewer comments we may take into consideration:

* Efficiency
The paper makes several efficiency claims, but in the absence of any experiments to back up these claims I would advise the authors to be a bit more cautious. Even if one disregards the cleaning of large ranges of memory, which could indeed be done with some extra hardware, the calling convention still seems more complicated than the usual ones. For instance, cleaning and restoring registers alone might make the overheads unacceptable in many practical scenarios. The "link table" seems to add overhead too, etc. Finally, "acceptable performance" is very much context dependent, for systems people that's less than 10-20% overhead, for crypto people it's 0 overhead.

* DONE Clarify attacker model earlier
The proposed calling convention seems able to protect multiple components from each other, yet most of the paper discusses this protection only in terms of one single statically known "adversary". This seems to be selling short the work, and raising questions of whether this calling convention is much weaker security-wise than the CHERI one, which is clearly about protecting multiple components. It would be good to explain this better upfront, not just in the discussions section at the end.
- Add this to section 3 in the introduction.

* DONE Make the title shorter
title is an extreme mouthful; in the first part could at least consider dropping the first "Capability", i.e. "Reasoning about a Machine with Local Capabilities"; also drop "(without OS support)", it's just too much, this is not yet the abstract

* DONE Rewrite abstract
The first two phrases in the abstract don't read very well and they have a large verbatim duplication

* DONE Move macro subsection to when it is used
Still didn't get why these macros are introduced at the end of Section 3. They are not used at all in Section 4, so isn't a more natural space for them the beginning of Section 5, where they are first used?

* Remove lemma 4 for more space
p19. Lemma 4. One more lemma that looks the same as all the others. Why not make some space for more interesting things by only stating the first such lemma formally?

* TODO Fix citations
p23. "Interestingly, [24] also use a step-indexed, Kripke logical relation" -- this should be "Hur et al [24]" (\citet), in general using citations as nouns is quite grose

p. 24 "[25]’s second-class or local value". Throughout the paper but especially here: never use a reference number such as [25] as a name.

* DONE Make forward pointer for stack executable
p.7 "The stack pointer is local and has RWLX permission." The X part raises a red flag! Maybe you could put a forward reference to the discussion two pages down ("Note that this means we will be placing and executing instructions on the stack")
